disabled_rules:
- trailing_whitespace
- force_cast
- function_body_length
- type_body_length
- file_length
- closure_parameter_position
- void_function_in_ternary
- line_length
- empty_enum_arguments
- type_name
- function_body_length

included:

excluded:
- Pods

line_length:

identifier_name:
    min_length:
        warning: 1
    allowedsymbols: [""]


trailing_whitespace:

